apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NaveenBalagouni/my-helm-chart
    path: my-helm-charts/single-helm-sample
    targetRevision: main
    helm:
      valueFiles:
      - values.yaml
      - template/deploy.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: single-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
