apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-helm-chart-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NaveenBalagouni/my-helm-chart.git'
    path: my-helm-charts/single-helm
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: single-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
