apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
spec:
  project: default
  source:
    repoURL: https://github.com/NaveenBalagouni/my-helm-chart
    targetRevision: HEAD
    path: my-charts  # Path to the specific chart directory if needed
    helm:
      valueFiles:
        - values.yaml  # Optional: specify values file
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
